### ISSUE TITLE
Support idle timeout in the client builder

### ISSUE THREAD

**Issue by lewisKendall-Jones** [lewisKendall-Jones/azure-sdk-for-java-jdk8-httpurlconnection-client#42]
See HttpUrlConnectionAsyncClientBuilderTests line 90.

**Comment by Jamelas** [comment]
Added `connectionTimeout` method, and connection timeout parameter to `build` method.

Because the `HttpUrlConnectionAsyncClientBuilderTests` is incomplete I cannot use this test class to see if the changes made have been successful.

I'll close this as stale as we have switched to the HttpClient test suite.
